#!/usr/bin/env bash

set -euo pipefail

if [ -t 0 ]; then
  versions_list=$@
else
  versions_list=$(cat)
fi

version_weight() {
    printf '%s\n' $1 |
    sed -r \
        -e 's:\+.*$::' \
        -e 's:^v::' \
        -e 's:^[0-9]+(\.[0-9]+)+$:&-stable:' \
        -e 's:([^A-Za-z])dev\.?([^A-Za-z]|$):\1.10.\2:g' \
        -e 's:([^A-Za-z])(alpha|a)\.?([^A-Za-z]|$):\1.20.\3:g' \
        -e 's:([^A-Za-z])(beta|b)\.?([^A-Za-z]|$):\1.30.\3:g' \
        -e 's:([^A-Za-z])(rc|RC)\.?([^A-Za-z]|$)?:\1.40.\3:g' \
        -e 's:([^A-Za-z])stable\.?([^A-Za-z]|$):\1.50.\2:g' \
        -e 's:([^A-Za-z])pl\.?([^A-Za-z]|$):\1.60.\2:g' \
        -e 's:([^A-Za-z])(patch|p)\.?([^A-Za-z]|$):\1.70.\3:g' \
        -e 's:\.{2,}:.:' \
        -e 's:\.$::' \
        -e 's:-\.:.:'
}

tags_orig=(${versions_list})
tags_weight=( $(version_weight "${tags_orig[*]}") )

keys=$(for ix in ${!tags_weight[*]}; do
    printf "%s+%s\n" "${tags_weight[${ix}]}" ${ix}
done | sort -V | cut -d+ -f2)

for ix in ${keys}; do
    printf "%s\n" ${tags_orig[${ix}]}
done
