name: Add channel
description: Add a version channel for a package
title: "feat(p): add channel <channel> for <package>"
labels: [p, add-channel]

assignees:
  - Toxikuu
body:
  - type: markdown
    attributes:
      value: |
        ## Add channel

  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the package
      placeholder: curl
    validations:
      required: true

  - type: input
    id: channels
    attributes:
      label: Channels
      description: The version channel(s) to add
      placeholder: unstable, sdk
    validations:
      required: true
